### ISSUE TITLE
`create-env` and `interpolate` behave differently with specific ops configuration

### ISSUE THREAD

**Issue by zaksoup** [cloudfoundry/bosh-cli#101]
### The Issue:
When using the vsphere cpi ops file, if you include a secondary ops file with the following contents:
```yaml
---
- type: replace
  path: /instance_groups/name=bosh/properties/vcenter/datacenters/name=((vcenter_dc))/clusters/0/((vcenter_cluster))/resource_pool?
  value: ((vcenter_rp))
```

`bosh interpolate` will succeed while `bosh create-env` will fail. The error is:

```
Started validating
Failed validating (00:00:00)

Parsing installation manifest '/Users/pivotal/workspace/bosh-deployment-2/bosh.yml':
  Evaluating manifest:
    Expected to find exactly one matching array item for path '/instance_groups/name=bosh/properties/vcenter/datacenters/name=((vcenter_dc))' but found 0

Exit code 1
```

#### interpolate (successful)
```bash
bosh int ~/workspace/bosh-deployment/bosh.yml \
  --ops-file ~/workspace/bosh-deployment/vsphere/cpi.yml \
  --ops-file ~/workspace/bosh-deployment/vsphere/specify-resource-pool.yml \
  -l ./vsphere-vars
```

#### create-env (errors)
```bash
bosh create-env ~/workspace/bosh-deployment/bosh.yml \
  --state ~/scratch/vsphere/director-state.json \
  --vars-store ~/scratch/vsphere/creds.yml \
  --ops-file ~/workspace/bosh-deployment/vsphere/cpi.yml \
  --ops-file ~/workspace/bosh-deployment/vsphere/specify-resource-pool.yml \
  -l ./vsphere-vars
```
