### ISSUE TITLE
Proposal: allow forks of bosh releases

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-cli#159]
I recently wanted to fork etcd-release so I could use a different etcd version. It wasn't simple; and the resulting repo - whilst itself a git fork - now has its own copy of every blob. It is a maintenance burden that seems beyond what a developer might expect in the current git fork dev flow they are used to.

I had an idea that might allow more easy maintenance of long running forks of bosh releases which will allow:

* continual reuse of upstream repo's blobs - src, package and jobs
* easy merging/rebasing with upstream git repo over time

TL;DR - flatten config/final.yml blobstore info into each and every item in blob yml references 

Currently the resolution of a blob requires the blob name/reference and the relative blobstore information from config/final.yml

But if you fork a bosh release and don't have config/private.yml for the upstream blobstore then you have to use a different final.yml and all the upstream blob refs don't work.

Instead: each blob ref would include its blobstore information - for s3 this would be the bucket name.

Now any blob ref could be found even if the repo's final.yml was changed within a fork.

**Comment by cppforlife** [comment]
yup, something i discussed over two years ago with some of the ibm folks.

> Instead: each blob ref would include its blobstore information - for s3 this would be the bucket name.

i think we would do it a bit more generically and have some kind of a blobostore ref name so that details can be updated without rewriting all the yaml files. may be a notion of a default.

we still would have a problem of merging upstream to forked copy so may be it deserves further separation so that resources are not reused based on a fingerprint.

**Comment by drnic** [comment]
So perhaps `config/final.yml` could include multiple blobstore references by name?

```yaml
---
final_name: dingo-postgresql-image
blobstores:
- name: cloudfoundry-community
  provider: s3
  options:
    bucket_name: dingo-postgresql-image-boshrelease
- name: drnic
  provider: s3
  options:
    bucket_name: my-bucket
```
