### ISSUE TITLE
behavior difference with old ruby cli when deploying cf-release

### ISSUE THREAD

**Issue by w7tek** [cloudfoundry/bosh-cli#16]
I've got a deployment that includes cf-release, and configures security groups.
Some of the entries for the security groups use `ports: "80,443"` in the deployment.yml.
The `cloud_controller_clock` job in cf-release consumes this config via `to_json` in the ERB templates.
When I run using the old ruby bosh cli, this template gets instantiated in the job as {..., "ports":"80,443", ...}, however with everything else the same and deploying using the new go bosh cli, this gets translated to JSON as {..., "ports": 80443, ...}. This causes the cloud_controller_clock to fail to start, because it expects a string value for ports and gets a numeric.

Hopefully that is enough info to reproduce the issue and see the problem; if not I may be able to pare it down to demonstrate the issue.

**Comment by dpb587-pivotal** [comment]
What does the exact property snippet from your manifest look like? Is this on the app security groups, or which specific `cloud_controller_click` property is seeing this?

**Comment by w7tek** [comment]
Here's a trimmed, sanitized example that is very similar to the actual data in my manifest:

```yaml
# configure the singleton vm
- name: singleton
  - name: cloud_controller_clock
    properties:
      cc:
        security_group_definitions:
        - name: google
          rules:
          - protocol: tcp
            destination: 216.58.195.78
            ports: "80,443"
```
