### ISSUE TITLE
CLI only generates Certs/RSA keypairs with a fixed length

### ISSUE THREAD

**Issue by schmidtsv** [cloudfoundry/bosh-cli#194]
Currently the CLI will only generate SSL Keys or RSA private keys with a length of 2048 bit. For better support of longer keys (for example in production environments) it should be possible to specify the key-length in the manifest. Example:

```yaml
- name: uaa_jwt_signing_key
  type: rsa
  options:
    bits: 8192
```
