### ISSUE TITLE
bosh loses trailing zeros when interpolating variables

### ISSUE THREAD

**Issue by ekcasey** [cloudfoundry/bosh-cli#208]
Given a manifest with a quoted variable reference

```
stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: "((stemcell-version))"
```
when I try to use a variable value with a trailing zero

```
bosh interpolate -v stemcell-version="3363.20" manifests.yml
```
the trailing zero is lost...

```
stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: 3363.2
```

The only way to preserve the trailing zero is to add quotes to the variable value
```
bosh interpolate -v stemcell-version="\"3363.20\"" manifests.yml
...
stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: "3363.20"
...
```
