### ISSUE TITLE
CLI should use canonical s3cli; instead uses an old fork of s3cli

### ISSUE THREAD

**Issue by cunnie** [cloudfoundry/bosh-cli#24]
Code: https://github.com/cloudfoundry/bosh-cli/blob/281ef97040c00319c9b4588483e9434184f83ba6/releasedir/s3_blobstore.go#L11

This fork is 200 commits behind the [s3cli](https://github.com/pivotal-golang/s3cli) and most likely doesn't work with many s3-compatible blobstores like Google Cloud Storage. Should we bump this dependency (will require minor code changes) to enable better release blobstore support?

**Comment by cunnie** [comment]
We noticed this when we tried to build the vsphere CPI on a fresh workstation:

```bash
bosh create-release  --tarball
Blob download 'vsphere_cpi_mkisofs/cdrtools-3.00.tar.bz2' (2.0 MB) (id: 93d9103d-44cf-47da-9343-49c1a4bea480 sha1: 6464844d6b936d4f43ee98a04d637cd91131de4e) started

Blob download 'vsphere_cpi_mkisofs/cdrtools-3.00.tar.bz2' (id: 93d9103d-44cf-47da-9343-49c1a4bea480) failed

Getting blob '93d9103d-44cf-47da-9343-49c1a4bea480' for path 'vsphere_cpi_mkisofs/cdrtools-3.00.tar.bz2':
  Getting blob from inner blobstore:
    Getting blob from inner blobstore:
      BucketRegionError: incorrect region, the bucket is not in 'us-east-1' region
       	status code: 301, request id:

Exit code 1
```

This was due to our `final.yml` missing an explicit region:

```yaml
---
final_name: bosh-vsphere-cpi
blobstore:
  provider: s3
  options:
    endpoint: https://s3-us-west-1.amazonaws.com
    bucket_name: bosh-vsphere-cpi-blobs
```

The latest s3cli is able to autodetect the region based on the hostname.
