### ISSUE TITLE
Ops file processing should happen before yml anchors are composed

### ISSUE THREAD

**Issue by pivotal-danjahner** [cloudfoundry/bosh-cli#254]
If I have a manifest like below and I apply an ops file to it, the behavior is unexpected to me. I would expect ops files to be processed before the anchors are composed. If this isn't the case, writing ops files gets very complicated with anchors. 

Manifest - 
```
instance_groups:
  jobs: 
  - name: db
    properties: 
      db: &db
        host: 127.0.0.1
        username: root
        password: test
  - name: client
    properties: 
      db: *db
  - name: complex
    properties:
      complex: &complex 
        db: *db
  - name: consumer
    properties:
      complex: *complex
```

Ops file - 
```
- type: replace 
  path: /instance_groups/jobs/name=db/properties/db/username
  value: admin
```

Actual result - 
```
instance_groups:
  jobs:
  - name: db
    properties:
      db:
        host: 127.0.0.1
        password: test
        username: admin
  - name: client
    properties:
      db:
        host: 127.0.0.1
        password: test
        username: root
  - name: complex
    properties:
      complex:
        db:
          host: 127.0.0.1
          password: test
          username: root
  - name: consumer
    properties:
      complex:
        db:
          host: 127.0.0.1
          password: test
          username: root
```

Expected result - 
```
instance_groups:
  jobs:
  - name: db
    properties:
      db:
        host: 127.0.0.1
        password: test
        username: admin
  - name: client
    properties:
      db:
        host: 127.0.0.1
        password: test
        username: admin
  - name: complex
    properties:
      complex:
        db:
          host: 127.0.0.1
          password: test
          username: admin
  - name: consumer
    properties:
      complex:
        db:
          host: 127.0.0.1
          password: test
          username: admin
```
