### ISSUE TITLE
Stemcells are not uploaded during deploy

### ISSUE THREAD

**Issue by achawki** [cloudfoundry/bosh-cli#261]
Hi,
when deploying a manifest with a Stemcell which has not been yet uploaded to the Director, e.g.:
```
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    sha1: b7f3096d1b2271317ec96c84e448e14d8b0a7429
    url: https://bosh.io:443/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3421.11
    version: "3421.11"
```

The bosh cli fails with:
```
07:42:41 | Deprecation: Ignoring cloud config. Manifest contains 'networks' section.
07:42:41 | Preparing deployment: Preparing deployment (00:00:00)
            L Error: Stemcell 'bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3421.11' doesn't exist

07:42:41 | Error: Stemcell 'bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3421.11' doesn't exist
```

The previous bosh cli uploaded the Stemcell if it didn't exist yet.

**Comment by cppforlife** [comment]
@achawki stemcell urls+sha are iaas specific. our goal is to keep our manifest iaas agnostic, hence we decided to keep out stemcell uploading functionality out of it.

**Comment by Kiemes** [comment]
I would be very much in favour of adding this feature as well as I also find it not convenient enough at the moment. 'create-env' does it already, but I have to admit, this is slightly different.

However, we should make this possible and keep the IaaS agnostic manifest at the same time. That would mean, we could put the stemcell URL and SHA1 into cloud-config. If you don't specify it, then require it to be already uploaded as it is right now.

Example:
cloud-config.yml
```
---
stemcells:
- name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
  sha1: b7f3096d1b2271317ec96c84e448e14d8b0a7429
  url: https://bosh.io:443/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3421.11
  version: "3421.11"
  alias: default

vm_types:
- name: small
...
```

You would not need to specify stemcells in the manifest at all, but 'bosh deploy' would merge manifest and cloud-config anyway and have the alias available which is used in instance_groups. Similar to 'networks' and 'vm_types'. Both are defined as IaaS agnostic in cloud-config and used in the manifest.

@cppforlife wdyt?
