### ISSUE TITLE
bosh interpolation with ports list

### ISSUE THREAD

**Issue by rauizab** [cloudfoundry/bosh-cli#271]
Hi
When we try to apply an ops file defining our security groups we are not able to map a list of ports
```
bosh int manifest.yml -o sg.yml
```
where our sg.yml is:
```
---
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/security_group_definitions
    - name: sgName
      rules:
      - destination: 10.*.*.*/28
        ports: "443,4443"
        protocol: tcp
```
results in the final manifest in:
```
name: sgName
rules:
- destination: 10.*.*.*/28
  ports: 443,4443 <<<<<<<<------------------- without double quotas
```
which fails in the deployment. We have tried with several options: ',\, "",ascii ....
We had to split that into 2 rules, one for every port.
It would be great if we could define a list of ports instead that having to define a list of rules.
