### ISSUE TITLE
S3 blobstore ignores folder option

### ISSUE THREAD

**Issue by dprotaso** [cloudfoundry/bosh-cli#274]
The previous CLI would work when we specified a nested folder

ie
```yaml
blobstore:
  provider: s3
  options:
    bucket_name: some-services
    folder: blobs
```

This no longer works with the bosh cli v2 - sync blobs errors out
