### ISSUE TITLE
bosh2 interpolate doesn't create expected certificates when they exist in deployment-vars.yml already

### ISSUE THREAD

**Issue by shalako** [cloudfoundry/bosh-cli#279]
I would like to construct a manifest to upgrade an existing deployment of cf-deployment to test a new manifest property.

Given a vanillla cf-deployment file that contains:

```
     router:
        ssl_cert: "((router_ssl.certificate))"
        ssl_key: "((router_ssl.private_key))"
```

and `variables` in cf-deployment contains:

```
- name: router_ssl
  type: certificate
  options:
    ca: router_ca
    common_name: routerSSL
    alternative_names:
    - "((system_domain))"
    - "*.((system_domain))"
```

When I replace `router.ssl_key` and `router.ssl_cert` with `router.tls_pem` in cf-deployment

```
      router:
         tls_pem:
         - "((router_ssl.certificate))((router_ssl.private_key))"
        - "((router_ssl_2.certificate))((router_ssl_2.private_key))"
```
and I add an additional variable for the second cert to cf-deployment

```
+- name: router_ssl_2
+  type: certificate
+  options:
+    ca: router_ca
+    common_name: test.foo.com
+    alternative_names:
+    - "test.foo.com"
+    - "*.test.foo.com"
```

And I use `bosh2 int` to generate a manifest
I currently see the resulting manifest contains only the original cert for `tls_pem`
I expect to find both certs
