### ISSUE TITLE
certificates are not regenerated when variable options are updated

### ISSUE THREAD

**Issue by shalako** [cloudfoundry/bosh-cli#280]
A manifest property has three variable references:
```
        tls_pem:
        - "((router_ssl.certificate))((router_ssl.private_key))"
        - "((router_ssl2.certificate))((router_ssl2.private_key))"
        - "((router_ssl3.certificate))((router_ssl3.private_key))"
```

variables are defined as
```
- name: router_ssl
  type: certificate
  options:
    ca: router_ca
    common_name: routerSSL
    alternative_names:
    - "((system_domain))"
    - "*.((system_domain))"
- name: router_ssl2
  type: certificate
  options:
    ca: router_ca
    common_name: routerSSL2
    alternative_names:
    - "((system_domain))"
    - "*.((system_domain))"
- name: router_ssl3
  type: certificate
  options:
    ca: router_ca
    common_name: routerSSL3
    alternative_names:
    - "((system_domain))"
    - "*.((system_domain))"
```

I've done a deploy but then I notice that all my certs were generated with the same alternative names. 

When I update the variable options and deploy
I expect to see a diff that indicates that two of the certs are being replaced.

Currently there is no diff, indicating no change.
