### ISSUE TITLE
YAML parser is not preserving the order when dealing with map keys

### ISSUE THREAD

**Issue by qu1queee** [cloudfoundry/bosh-cli#290]
We have been seeing unexpected CF components being updated when deploying `zero` changes via bosh2. This tells me that we have indeed some changes in the manifest we intend to deploy, but somehow bosh2 is not detecting them.

I use the `bosh2 interpolate` to reproduce the error, which I believe should be using the same YAML parser when triggering a `bosh2 deploy`.

When doing the following command multiple times you can see how the map keys order change.

` bosh2 interpolate manifest.yml --path /properties/cc/quota_definitions` where `properties.cc.quota_definitions` is map of keys.

output changes during different runs:

-1 
```
q2GB:
  something: nothing
q4GB:
  something: nothing
q8GB:
  something: nothing
q16GB:
......
```

-2
```
q4GB:
  something: nothing
q8GB:
  something: nothing
q16GB:
  something: nothing
.....
```

The example above is causing our Cloud Controllers to be updated, which is not the expected behaviour.

Regards,

Enrique Encalada
