### ISSUE TITLE
Error not returned when asking for `latest` version of a release not on the director

### ISSUE THREAD

**Issue by jpalermo** [cloudfoundry/bosh-cli#295]
We added an operations file to an existing deployment:
```
---
- type: replace
  path: /releases/-
  value:
    name: consul
    version: latest
```

But our director didn't have this release uploaded yet. Rather than returning an error when attempting to deploy, it showed us an empty manifest change set and prompted us to deploy:
```
Continue? [yN]:
```

There were other changes in the operations file that also were not shown in the diff.
