### ISSUE TITLE
Longer/32-char password variable

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-cli#302]
Currently variables with `type: password` will be 20 characters long. https://bosh.io/docs/variable-types.html

When I was deploying mattermost, it requires a 32-char encryption key. Could we extend `type: password` to allow generation of longer passwords?

Or, can we make passwords longer by default? In credhub docs the example password looks to be 40+ characters https://docs.cloudfoundry.org/credhub/credential-types.html

Credhub also looks to have an `options.length` property for its variables. https://docs.cloudfoundry.org/credhub/credential-types.html#deployment-manifest Could we add this to the bosh-cli too?

```
- name: mattermost-sql-atrestencryptkey
  type: password
  options:
    length: 32
```

**Comment by cppforlife** [comment]
@drnic is this for create-env scenario or just vars-store?

**Comment by Rukenshia** [comment]
Please make the length dynamic, I wanted to deploy concourse with a generated encryption_key, but it required 16 or 32 characters. bosh only allows me to generate 20 character passwords.

**Comment by forbushbl** [comment]
I just tested this with a similar yml to what Dr. Nic proposed and it seems to be working. Perhaps this issue could be closed?

**template.yml**
```
- name: credhub_database_password
  type: password
  options:
    length: 64
```

Command I ran:
`bosh interpolate template.yml --vars-store=creds-out.yml`

I tried both 64 and 6 for the length and both worked.
