### ISSUE TITLE
bosh create-env returns confusing error when missing release key

### ISSUE THREAD

**Issue by cdutra** [cloudfoundry/bosh-cli#346]
bosh-cli v2.0.44

Sample manifest:
```
instance_groups:
- name: openvpn
  jobs:
  - name: openvpn
     properties: {}
```

bosh create-env will fail and return the following error message:
```
Validating deployment manifest:
  - jobs[0].templates[0].release must be provided

Exit code 1
```
