### ISSUE TITLE
How about CLI use 'address' property to install CPI locally same as the director

### ISSUE THREAD

**Issue by edwardstudy** [cloudfoundry/bosh-cli#350]
Hi, I found that CLI install local CPI by parse installation manifest and set a registry property `host`  with 127.0.0.1 in [source code](https://github.com/cloudfoundry/bosh-cli/blob/687a73d443f383358be2374d6b453d3e383231a1/installation/manifest/parser.go#L133):
```
installationManifest.PopulateRegistry("registry", password, "127.0.0.1", 6901, comboManifest.CloudProvider.SSHTunnel)
```

And when deploying director, we must also set it to install the cpi job in director VM.

It made the registry property too redundant like this:
```
registry:
  address: ((internal_ip))
  host: ((internal_ip))
  db: # todo remove
    host: 127.0.0.1
    user: postgres
    password: ((postgres_password))
    database: bosh
    adapter: postgres
  http:
    user: registry
    password: ((registry_password))
    port: 25777
  username: registry   
  password: ((registry_password))
  port: 25777
```

And the CPI can use `address` in director job to render its cpi.json file and be set up. The relative issue to shorten properties is [#1](https://github.com/cloudfoundry/bosh-cli/issues/80) .

So why don't change 'host' to 'address'  in installation manifest? That can make the CPI use the same address to render config file.

And I knew that it results in the change in every existing CPI template. But I still hope we can think about it.

Thank you.
