### ISSUE TITLE
bosh int doesn't show variables generated when --vars-store flag is present

### ISSUE THREAD

**Issue by zmb3** [cloudfoundry/bosh-cli#389]
When the `--vars-store` flag is present, variables that are generated do not show up in the interpolated `variables:` section.  This led me to believe that interpolation wasn't working when it was.

```
❯ cat base.yml
foo:
  bar: 1
  baz:
  - a
  - b

❯ cat add-vars.yml
- type: replace
  path: /variables?/name=password?
  value:
    name: password
    type: password

❯ bosh int base.yml -o add-vars.yml
foo:
  bar: 1
  baz:
  - a
  - b
variables:
- name: password
  type: password

Succeeded

❯ bosh int base.yml -o add-vars.yml --vars-store store.yml
foo:
  bar: 1
  baz:
  - a
  - b
variables: []

Succeeded
```

Notice how the variables section includes the `password` variable in the first example, but then appears empty `variables: []` when I use a `--vars-store`.
