### ISSUE TITLE
Add ability to use yaml references in operator files that refer to the main yaml

### ISSUE THREAD

**Issue by haydonryan** [cloudfoundry/bosh-cli#398]
I'm trying to write an operations file to co-locate the concourse web and db jobs onto one vm. 

[https://github.com/concourse/concourse-deployment/blob/master/cluster/concourse.yml](https://github.com/concourse/concourse-deployment/blob/master/cluster/concourse.yml)

If I use replace to add the db job to web:
```
- type: replace
  path: /instance_groups/name=web/jobs/-
  value:
    release: postgres
    name: postgres
    properties:
      databases:
        port: 5432
        databases:
        - name: *db_name
        roles:
        - *db_role
```
Then I get an error becasue the anchor is outside of the ops file...
```
invalid argument for flag `-o, --ops-file' (expected []cmd.OpsFileArg): Deserializing ops file 'colocate-db.yml': yaml: unknown anchor 'db_name' referenced
```

Is there a way that you could either 
a) support yaml anchors spanning files or
b) add to replace the ability to replace a path with another path. (in effect a copy)?
