### ISSUE TITLE
Idea: Providing links in CLI for external consumption

### ISSUE THREAD

**Issue by dpb587** [cloudfoundry/bosh-cli#402]
Links are technically a director thing right now, but I was thinking that if the CLI was able to consume [manual (to start)] provided links in the same/similar way to director manifests, it could enable some integrations with external tooling, and possibly save users from some common steps they currently perform after `create-env`.

For example, the most common use case of `create-env` is creating a director. There is almost always a second step which then gets executed to configure it for the user via `alias-env`. If we treated links as a way to communicate settings outside of the manifest, we might be able to have some fun.

```
# /instance_groups/name=bosh/jobs/name=director
    provides:
      bosh:
        type: bosh-director
        properties:
          environment: ((director_name))
          ca_cert: ((director_ssl.ca))
          client: admin
          client_secret: ((admin_password))
```

There could then be an `--autoalias`-type option for `create-env` which takes an extra step for finishing the `create-env` command by trying to alias links of particular types that it recognizes. For `bosh-director`, it's essentially just `alias-env`.

If generalizing to other components, this also becomes a possibility for things like Concourse's `fly`. We wouldn't want `fly`/external-specifics in the codebase, so it would require a bit more generalization. One generalization could be that it serializes these links to files which could then be consumed other tools. For example, if the CLI wrote out provided links as files...

```
name: bosh
type: bosh-director
instances:
- address: 10.0.0.6
properties:
  environment: bosh-lite
  ca_cert: ===...
  client: admin
  client_secret: top
```

Other tools could provide commands such as `import-env` which know how to parse and load the format. With research, there's probably a more standardized way to write out the information as well, to avoid making it BOSH-specific.

If generalizing with a link spec-type output isn't enough, another provided link type which I could see being useful might be a simple `file` type. The `file` types then just get written to the system whenever the `--register`/`--consume-links`/`--export-links`/whatever arg would be used.

```
# /instance_groups/name=bosh/jobs/name=director
    provides:
      bosh_envrc:
        type: file
        properties:
          path: .envrc
          content: |
            export BOSH_ENV="((internal_ip))"
            export BOSH_CA_CERT="((director_ssl.ca))"
            export BOSH_CLIENT="admin"
            export BOSH_CLIENT_SECRET="((admin_password))"
```

Thoughts?
