### ISSUE TITLE
bosh deploy/upload-release command should support --version create flag when url is git+https

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/bosh-cli#411]
currently bosh deploy command supports `version: create` so that release is automatically created from local directory. it would be nice to support creation of a release if url is git+https so that manual step of git cloning could be eliminated.

```
releasees:
- name: kafka
  url: git+https://github.com/cppforlife/kafka-release
  version: create
```
