### ISSUE TITLE
Allow escaping in operation file paths

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry/bosh-cli#457]
If a value has a `/` in it, for instance here:

https://github.com/cloudfoundry/bosh-deployment/blob/beaa4fd5efbcfbafc7d70a406cbd8c1c0b751f16/runtime-configs/dns.yml#L68

Is it possible to replace this since the `/` is part of the operation file syntax.

I would like to turn this:

```yaml
variables:
- name: /test
  value: bar
- name: other-test
  value: baz
```

into this:

```yaml
variables:
- name: other-test
  value: baz
```

using an ops file that looks something like this:

```yaml
- type: remove
  path: /variables/name=\/test
```
