### ISSUE TITLE
Problems to use gcs as blobstore

### ISSUE THREAD

**Issue by jraverdy-orange** [cloudfoundry/bosh-cli#483]
Hi,

I'm actually unable to use gcs as blobstore. Even if i perform `bosh upload-blobs` or `bosh create-release`, i encounter the following error:

```
Creating blob in inner blobstore:
	unknown location
```

Here is my final.yml

```yaml
---
final_name: test
blobstore:
  provider: gcs
  options:
    bucket_name: bucket-test
```
and my private.yml

```yaml
---
blobstore:
  options:
    credentials_source: static
    json_key: |
          {
            "type": "service_account",
            "project_id": "*****",
            "private_key_id": "***",
            "private_key": "-----BEGIN PRIVATE KEY-----\n*****\n-----END PRIVATE KEY-----\n",
            "client_email": "bosh-test@***.iam.gserviceaccount.com",
            "client_id": "***",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/bosh-test%40******.iam.gserviceaccount.com"
          }

```

I have no problem to do operations on bucket using gsutl tool with the same json file.

the bucket seems to be well reached as if i change the bucket name with an unexisting one in final.yml, i get 

```
    Creating blob in inner blobstore:
      storage: bucket doesn't exist
```
Is there something i don't do well ?
