### ISSUE TITLE
Invalid type 'float64' for value 'XXX' and variable 'XXX'. Supported types for interpolation within a string are integers and strings.

### ISSUE THREAD

**Issue by brightzheng100** [cloudfoundry/bosh-cli#484]
I encountered a weird issue, as below.

**Error:**

```
Evaluating manifest:
  Invalid type 'float64' for value '60.2' and variable 'uaa_version'. Supported types for interpolation within a string are integers and strings.
```

**Command:**

```
bosh -e lite deploy -d xxx xxx.yml \
  --vars-store cluster-creds.yml \
  -o operations/uaa.yml \
...
  -v uaa_version='60.2'
```

**uaa.yml:**

```
- type: replace
  path: /releases/-
  value:
    name: uaa
    url: "https://bosh.io/d/github.com/cloudfoundry/uaa-release?v=((uaa_version))"
    sha1: ((uaa_sha1))
    version: "((uaa_version))"
...
```

It can work only when I set the value like this pattern: `-v uaa_version='"60.2"'`.

**Error in both `bosh cli` versions tested:**

```
bosh -version
version 2.0.48-e94aeeb-2018-01-09T23:08:08Z
```
and
```
$ bosh -version
version 5.3.1-8366c6fd-2018-09-25T18:25:48Z
```
