### ISSUE TITLE
create-env is failing rendering else_if_p template accessor

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/bosh-cli#516]
I'm trying to use `bosh create-env` (through bbl) to deploy the jumpbox deployment with the following ops file:

```yml
- type: replace
  path: /instance_groups/name=jumpbox/jobs/-
  value:
    name: haproxy
    release: haproxy
    properties:
      ha_proxy:
        disable_http: true
        log_level: debug
        tcp:
        - name: internet-proxy
          port: 3128
          backend_port: 80
          backend_servers:
          - 192.168.10.1

- type: replace
  path: /releases/name=haproxy?
  value:
    name: "haproxy"
    version: "8.6.1"
    url: "https://bosh.io/d/github.com/cloudfoundry-community/haproxy-boshrelease?v=8.6.1"
    sha1: c34f21cee8b3f31d25467c7f0a4e4472da8e1585
```

The `bosh create-env` command eventually fails with the following trace

```
Deploying:
  Building state for instance 'jumpbox/0':
    Rendering job templates for instance 'jumpbox/0':
      Rendering templates for job 'haproxy/d3520b21f0ad2fd9efb5765eb4b48da592315251':
        Rendering template src: haproxy.config.erb, dst: config/haproxy.config:
          Rendering template src: /home/gberche/.bosh/installations/f6468893-92a8-4c30-6a3b-6503a3a65b7e/tmp/bosh-release-job097381512/templates/haproxy.config.erb, dst: /home/gberche/.bosh/installations/f6468893-92a8-4c30-6a3b-6503a3a65b7e/tmp/rendered-jobs513551916/config/haproxy.config:
            Running ruby to render templates:
              Running command: 'ruby /home/gberche/.bosh/installations/f6468893-92a8-4c30-6a3b-6503a3a65b7e/tmp/erb-renderer642694600/erb-render.rb /home/gberche/.bosh/installations/f6468893-92a8-4c30-6a3b-6503a3a65b7e/tmp/erb-renderer642694600/erb-context.json /home/gberche/.bosh/installations/f6468893-92a8-4c30-6a3b-6503a3a65b7e/tmp/bosh-release-job097381512/templates/haproxy.config.erb /home/gberche/.bosh/installations/f6468893-92a8-4c30-6a3b-6503a3a65b7e/tmp/rendered-jobs513551916/config/haproxy.config', stdout: '', stderr: '/home/gberche/.bosh/installations/f6468893-92a8-4c30-6a3b-6503a3a65b7e/tmp/erb-renderer642694600/erb-render.rb:189:in `rescue in render': Error filling in template '/home/gberche/.bosh/installations/f6468893-92a8-4c30-6a3b-6503a3a65b7e/tmp/bosh-release-job097381512/templates/haproxy.config.erb' for haproxy/0 (line 299: #<NoMethodError: undefined method `else_if_p' for false:FalseClass>) (RuntimeError)
        from /home/gberche/.bosh/installations/f6468893-92a8-4c30-6a3b-6503a3a65b7e/tmp/erb-renderer642694600/erb-render.rb:174:in `render'
        from /home/gberche/.bosh/installations/f6468893-92a8-4c30-6a3b-6503a3a65b7e/tmp/erb-renderer642694600/erb-render.rb:200:in `<main>'
':
                exit status 1
```

which corresponds to https://github.com/cloudfoundry-incubator/haproxy-boshrelease/blame/v8.6.1/jobs/haproxy/templates/haproxy.config.erb#L299 which renders properly in a full fledged bosh director.

While I could not find the `else_if_p` template accessor documented in bosh.io (likely close to https://bosh.io/docs/links/#templates) there seems indeed support in bosh-cli

https://github.com/cloudfoundry/bosh-cli/blob/a18c72307483843b5e190c383ff5e6835b3a8bf2/templatescompiler/erbrenderer/template_evaluation_context_rb.go#L143-L145

This problem reproduced with the following bosh-cli version installed on ubuntu bionic (see related https://github.com/cloudfoundry/docs-bosh/pull/627 for os reqs installed)
```
bosh -v
version 5.4.0-891ff634-2018-11-14T00:22:02Z
```

In case this may help, here is the ruby version details:

```
#  ruby --version
#  ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
```
