### ISSUE TITLE
CreateEnv ignores cloud properties on manual networks when specified at root level

### ISSUE THREAD

**Issue by ships** [cloudfoundry/bosh-cli#532]
Hi friends

I have diagnosing a create-env that has been failing in surprising ways, like `Expected to find network ''`, when using this manifest:
```
networks:
- name: default
  cloud_properties: {name: x, type: garbage}
  subnets:
  - dns:
    - 8.8.8.8
    gateway: 192.168.1.254
    range: 192.168.1.0/24
    static:
    - 192.168.1.20
  type: manual
- cloud_properties:
    name: NatNetwork
    type: natnetwork
  name: outbound
  type: dynamic
```

among other things, was startled to learn that the `garbage` type specification did not cause an error when i expected.

So looking thru the code I noticed [this switch](https://github.com/cloudfoundry/bosh-cli/blob/develop/deployment/manifest/network.go#L58-L60) which was resulting that because my first network was manual type, its cloud properties were ignored until i nested them under the first subnet. i was able to confirm in my debug logs that the manual network was being attached with no cloud properties.

is this intentional? i can't really see a reason for this logic as opposed to merging the cloud_properties in, and it produces a non-obvious discrepancy in behavior in the two cases.
