### ISSUE TITLE
Use of cartesian-product in bosh ops files

### ISSUE THREAD

**Issue by sravankumar777** [cloudfoundry/bosh-cli#544]
In bosh-ops files, we have defined IP address & some specific ports in separate files for overrides to be used in our deployment. 

We have below configuration: 
```
node_ips:
- 100.100.110.101
- 100.100.110.102
- 100.100.110.103

node_ports: 2003
```
Now, we would like to use these two properties for another job in below fashion.
```
jobs:
- name: job1
   release: job-release
   properties:
      node_properties:
      - 100.100.110.101: 2003
      - 100.100.110.102: 2003
      - 100.100.110.103: 2003
```
I tried to grab the node ip information using indices, but this operation did not worked in our bosh ops files as shown below.
```
jobs:
- name: job1
   release: job-release
   properties:
      node_properties:
      - ((node_ips[0])):((node_port))
      - ((node_ips[1])):((node_port))
      - ((node_ips[2])):((node_port))
```

Do we have support of cartesian-product operation in bosh-ops just like in Spruce.
