### ISSUE TITLE
Difference how interpolate and create-env work with ops-files and remove

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh-cli#66]
I'm using bosh-deployment with the keystone v3 opsfile to deploy a Director. 

`bosh interpolate bosh.yml --ops-file openstack/cpi.yml --ops-file openstack/keystone-v3.yml -l secrets.yml -l openstack-secrets.yml -l outer-creds.yml --var-errs` works and creates an output with an `openstack` section like this:
```
openstack:
      api_key: <redacted>
      auth_url: <redacted>
      default_key_name: bosh
      default_security_groups: bosh
      domain: <redacted>
      project: <redacted>
      region: null
      username: <redacted>
```

Note that `domain` and `project` are in there, while `tenant` is not.

Here is what I get on `bosh create-env bosh.yml --ops-file openstack/cpi.yml --ops-file openstack/keystone-v3.yml -l secrets.yml -l openstack-secrets.yml -l outer-creds.yml`:

```
Parsing installation manifest '/home/vcap/workspace/bosh-deployment/bosh.yml':
  Evaluating manifest:
    Expected to find a map key 'tenant' for path '/instance_groups/name=bosh/properties/openstack/tenant'

Exit code 1
```

Seems like the tenant remove operation in [openstack/keystone-v3.yml](https://github.com/cloudfoundry/bosh-deployment/blob/master/openstack/keystone-v3.yml#L10-L11) is failing in `create-env` but works in `interpolate`?
Or does `create-env` try to find a replacement for the `((tenant))` variable before the ops-file which removes it is applied? Are there two different paths for `interpolate` and `create-env`?
