### ISSUE TITLE
[ops-files] yaml anchors get removed when replacing properties in a hash

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh-cli#67]
The `openstack/cpi.yml` opsfile defines its cpi properties like this:
```
- type: replace
  path: /instance_groups/name=bosh/properties/openstack?
  value: &openstack
    auth_url: ((auth_url))
    username: ((openstack_username))
    api_key: ((openstack_password))
    tenant: ((tenant))
    region: ((region))
    default_key_name: ((default_key_name))
    default_security_groups: ((default_security_groups))
```

Note that this includes the yaml anchor `&openstack` in the value.

I added an ops-file that puts an additional property into the `openstack` hash above. The idea was to set connection options. Could have been any other extra property on the `openstack` hash as well (such as `default_volume_type`):
```
- type: replace
  path: /instance_groups/name=bosh/properties/openstack/connection_options?
  value:
    ca_cert: <redacted>
```

End result: The interpolated manifest looks good in the `instance_groups.bosh.properties.openstack section`, but `cloud_provider.properties.openstack` doesn't exist anymore. Most likely, because the yaml anchor is `nil`?
