### ISSUE TITLE
Support glob expansion in file url's for releases section

### ISSUE THREAD

**Issue by drich10** [cloudfoundry/bosh-cli#72]
Currently the cli does not support this and as a result I have to do some bashy workarounds to evaluate the path before handing it off to the manifest. For example

Given an override section
```
- type: replace
  path: /releases/-
  value:
    name: my-release
    version: some-version
    url: ((path_to_my_release))
```
and a hopeful bosh deploy command
```
bosh deploy -o foo.yml --var "path_to_my_release=file://path/to/release/*tgz"
```

what I am doing now to work around the lack of expansion:
```
bosh deploy -o foo.yml --var "path_to_my_release=file://$(ls path/to/release/*tgz)"
```

- @drich10 & @wendorf
