### ISSUE TITLE
Additional stemcell upload support

### ISSUE THREAD

**Issue by dpb587** [cloudfoundry/bosh-cli#73]
I think it would be convenient if the CLI could upload remote/local stemcells for me when I run `bosh deploy`, similar to how releases are handled and `create-env` work. Currently I store the stemcell info (name, url, sha1, version) in a separate file - first extracting it into an `upload-stemcell` command, then interpolate (name, version) into the deployment manifest. It would be very convenient to skip the `upload-stemcell` type of calls.

```yaml
- type: replace
  path: /stemcells/-
  value:
    alias: default
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    url: https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3312.3
    sha1: aabdf995a9ff68ab95453c76da15d2b7b8895a40
    version: 3312.3
```

I suppose `version` would not be allowed to be `latest`, and `version` could also be used to check if the stemcell already exists before asking it to do a naive remote download of the full stemcell tarball.

Does the feature seem reasonable; and have any other considerations around it?
