### ISSUE TITLE
CLI doesn't use original registry connection properties

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/bosh-cli#80]
BOSH CLI and CPIs uses different registry connection properties than required by the director and registry job. BOSH CLI [uses](https://github.com/cloudfoundry/bosh-cli/blob/47ea06453290186de2610150498d3901d16c4131/installation/manifest/manifest.go#L40):
```
registry.username
registry.password
registry.port
```

BOSH [director](https://github.com/cloudfoundry/bosh/blob/master/jobs/director/spec#L399-L402) and [registry](https://github.com/cloudfoundry/bosh/blob/master/jobs/registry/spec#L15) use:
```
registry.http.user
registry.http.password
registry.http.port
```

Users writing the manifest need to specify both at the moment. We would like to always use the original registry properties defined by the registry job. So the user and CPIs can remove duplicate values.

Current manifest example from bosh.io:
```
    registry:
      address: PRIVATE-IP # <--- Replace with a private IP
      host: PRIVATE-IP # <--- Replace with a private IP
      db: *db
      http:
        user: admin
        # password: admin # <--- Uncomment & change
        port: 25777
      username: admin
      # password: admin # <--- Uncomment & change
      port: 25777
```
