### ISSUE TITLE
CLI interpolation doesn't handle '/' in variable names 

### ISSUE THREAD

**Issue by danjahner** [cloudfoundry/bosh-cli#97]
To be consistent with the config server implementation, I should be able to specify variable names that include forward slash characters '/'. These currently generate appropriately, but they do not interpolate. 

For example - 

Manifest  
```
variables:
- name: uaa/users/admin
  type: password
- name: uaa/users/hm
  type: password
```

Generated values - 
```
uaa/users/admin: mov2ezwbrpb3eyqpkuc2
uaa/users/hm: 9nee3996jbw9r50do2eq
```

Interpolation - 
```
        scim:
          users:
          - groups:
            - scim.write
            - scim.read
            - bosh.admin
            name: admin
            password: ((uaa/users/admin))
          - groups:
            - bosh.admin
            name: hm
            password: ((uaa/users/hm))
```

Using version 0.0.142-fbd1696-2017-01-04T22:58:24Z
