### ISSUE TITLE
Certificates lacking CA are generated as self-signed CAs

### ISSUE THREAD

**Issue by pivotal-danjahner** [cloudfoundry/bosh-cli#98]
If I defined a certificate variable without a CA, like shown below, it should generate a self-signed leaf certificate with alternative names. It is currently generating this as a CA (basic constraints - CA: TRUE; no subject alternative names). 

```
variables:
- name: tls
  type: certificate
  options:
    common_name: *external_ip
    alternative_names:
    - *external_ip
    - *local_ip
```

Self-signed certificates should not have the basic constraints extension value 'CA: TRUE' . When I trust the certificate on my machine, my intention is to directly trust the self-signed certificate only. If this certificate is configured as a CA, my trust of it extends to any leaf certificates that it has signed.
